name = "coinbase-onramp-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
account_id = "9ee018e54b2e51abe3f976f6df6b33e5"

[vars]
ALLOWED_ORIGINS = "https://confetti.win"
